spring:
  application:
    name: one-mv-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #数据库连接配置
  hikari:
    from:
      jdbc-url: jdbc:mysql://sh-cdb-b2gvjfuq.sql.tencentcdb.com:59335/one?characterEncoding=utf-8&useSSL=false
      username: one
      password: One7777&
    to:
      jdbc-url: jdbc:mysql://one.jingsky.com:3306/one?characterEncoding=utf-8&useSSL=false
      username: one
      password: One6666^

#maxwell相关的配置
maxwell:
  tablePrefix: "t_mv_"